steps:
- name: 'gcr.io/cloud-builders/kubectl'
  args: 
  - set
  - image
  - deployment/spring-boot-contatiner
  - gcr.io/plated-courier-230214/spring-boot-container-test:latest
  - -n
  - spring-boot
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=asia-northeast1-b'
  - 'CLOUDSDK_CONTAINER_CLUSTER=spring-boot-contatiner-cluster'
options:
  machineType: 'N1_HIGHCPU_8' # HIGHCPU로 빌드 스피드 업
timeout: 1000s # 빌드 자체에 대한 타임 아웃
